name 'tribily-xtrabackup'
version '1.1.1'

author 'Walter Heck'
license 'Apache License, Version 2.0'
project_page 'https://github.com/Tribily/puppet-xtrabackup'
source 'git://github.com/Tribily/puppet-xtrabackup'
summary 'xtrabackup module'
description 'Module for Percona XtraBackup'
dependency 'tribily/apt', '==1.0'
